apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-lozj-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios@sha256:c434385d741f00b01afc8ee32b17ff160fa581a3b97e6fd59bbfe7bb57d4687c
        name: my-python
        resources: {}
status: {}
